# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.9.13               # https://pyreadiness.org/3.9/ 
  - pip=22.1.2                  # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here -> https://pypi.org/
      - robocorp-tasks==1.0.0      # https://pypi.org/project/robocorp-tasks/#history
      - robocorp-vault==0.4.0      # https://pypi.org/project/robocorp-vault/#history
      - robocorp-workitems==1.0.1  # https://pypi.org/project/robocorp-workitems/#history
      - openai==0.27.8             # https://pypi.org/project/openai/#history
      - rpaframework==23.3.0       # https://rpaframework.org/releasenotes.html